### ISSUE TITLE
Emails not sending

### ISSUE THREAD

**Issue by zmiguel** [range-of-motion/budget#153]
**Expected behavior**

Send email for registration, password reset, etc

**Current behavior**

email doesn't send with the error: 
```
Swift_TransportException: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients
```

**More information**

Running v0.4.0
I've setup this on my server and edited my .env file with the following 
```
MAIL_DRIVER=smtp
MAIL_HOST=mail.<my domain>.tld
MAIL_PORT=587
MAIL_USERNAME=no-reply@<my domain>.tld
MAIL_PASSWORD=<the password>
MAIL_ENCRYPTION=tls
```

I've tried both tls, starttls on port 587 and SSL on port 465

the mail server runs mailcow and works on different apps, including other laravel based apps

the destination email is a @gmail.com address. Also tried adding the MAIL_FROM_ADDRESS and MAIL_FROM_NAME to the .env file with no luck.

**Comment by range-of-motion** [comment]
Mh, weird. Can you try with a different service, like [Mailtrap](https://mailtrap.io/)?

**Comment by zmiguel** [comment]
@range-of-motion How would I try that?

**Comment by range-of-motion** [comment]
Set up an account, and use the credentials they provide for your `.env`. Or try another e-mail provider.

Also, the other Laravel projects that *do* work, do you have a link to their repository? Perhaps I can compare the changes that way.

**Comment by zmiguel** [comment]
Just tried it with gmail and amazon ses, both got the same error. same SES config I use on my relay and made sure to set the from address to one verified in SES.

The other project that has been working is: https://github.com/eveseat/seat

**Comment by zmiguel** [comment]
The full exception in case that helps:
<details>

```
Swift_TransportException: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients
" in /var/www/budget/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457
Stack trace:
#0 /var/www/budget/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('554 5.5.1 Error...', Array)
#1 /var/www/budget/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('DATA\r\n', Array, Array, false, NULL)
#2 /var/www/budget/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(390): Swift_Transport_EsmtpTransport->executeCommand('DATA\r\n', Array, Array)
#3 /var/www/budget/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(497): Swift_Transport_AbstractSmtpTransport->doDataCommand(Array)
#4 /var/www/budget/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'hello@example.c...', Array, Array)
#5 /var/www/budget/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'hello@example.c...', Array, Array)
#6 /var/www/budget/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /var/www/budget/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /var/www/budget/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(288): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /var/www/budget/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(177): Illuminate\Mail\Mailer->send('emails.reset_pa...', Array, Object(Closure))
#10 /var/www/budget/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}()
#11 /var/www/budget/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(178): Illuminate\Mail\Mailable->withLocale(NULL, Object(Closure))
#12 /var/www/budget/vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(52): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\MailManager))
#13 [internal function]: Illuminate\Mail\SendQueuedMailable->handle(Object(Illuminate\Mail\MailManager))
#14 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#15 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#17 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 /var/www/budget/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#20 /var/www/budget/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#21 /var/www/budget/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#22 /var/www/budget/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Mail\SendQueuedMailable), false)
#24 /var/www/budget/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#25 /var/www/budget/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#26 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Mail\SendQueuedMailable))
#28 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#29 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#30 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#31 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#32 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#33 /var/www/budget/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#34 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#35 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#36 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#37 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#38 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#39 /var/www/budget/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#40 /var/www/budget/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#41 /var/www/budget/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#42 /var/www/budget/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#43 /var/www/budget/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/budget/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/budget/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/budget/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /var/www/budget/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /var/www/budget/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 {main}
```

</details>

**Comment by range-of-motion** [comment]
Right, that means that you have no `MAIL_FROM_ADDRESS` defined in your `.env`. 

Perhaps you have done this in the meanwhile, but be aware that e-mails that were queued *before* you've modified your `.env` will still have the wrong e-mail address.

**Comment by zmiguel** [comment]
But I do, my .env file has mail_from_address set to the username. I've also modified config/mail.php with that same mail_from_address, and the address on line 5 doesn't change.

<details>

```
MAIL_DRIVER=smtp
MAIL_HOST=mail.<domain.tld>
MAIL_PORT=587
MAIL_USERNAME=alerts@<domain.tld>
MAIL_PASSWORD=<mypassword>
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=alerts@<domain.tld>
MAIL_FROM_NAME='Budget Notifications'

```

</details>

**Comment by range-of-motion** [comment]
> Perhaps you have done this in the meanwhile, but be aware that e-mails that were queued before you've modified your .env will still have the wrong e-mail address.

**Comment by zmiguel** [comment]
well, yeah. I just tried it again by registering a new account and trying a password reset, and got the error again

**Comment by range-of-motion** [comment]
Does the stacktrace still show `hello@example.com` as the e-mail address?

**Comment by zmiguel** [comment]
Yes, the last one I posted was from the test 15 minutes ago. that's what's confusing me, even after I changed the from address on the 2 possible places it is still trying to send from that address. 

I've even been running `php artisan config:cache` to make sure there's no cache with old settings.

Not really sure where else it could be getting that email from.

**Comment by range-of-motion** [comment]
How are you serving the app, using `php artisan serve`?

**Comment by zmiguel** [comment]
Followed the installation instructions in the readme file and I'm serving it with Nginx. cron and worker configured and, apparently, running.

**Comment by range-of-motion** [comment]
Ahh, wait! Did you restart the queue worker?

**Comment by zmiguel** [comment]
ah! that was it, restarted supervisor and it's working now. That's great!

Thanks for the help @range-of-motion

**Comment by range-of-motion** [comment]
Yeah, so basically the queue worker isn't aware of any changes made to environment variables until it's being restarted 😅
